# Generated by Django 4.2.16 on 2024-11-19 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('body_type', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurements',
            name='determined_body_type',
        ),
        migrations.RemoveField(
            model_name='bodymeasurements',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='body_type.bodytype'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
