# Generated by Django 4.2.16 on 2024-11-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body_type', '0002_remove_bodymeasurements_determined_body_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='chest',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hips',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='BodyMeasurements',
        ),
    ]
